#Edit this yaml file according to your needs.
Reminders:
  Morning : {'10:53':'Wake Up call for DSM!', '11:56':"Learn Python!!"}
  Evening: {'12:00':"Get Ready for War Room",'12:11':"Get Ready for War Room", '08:03': "Now it's time for Coding Round", '08:28': "Hello!!!"}